name: test go app 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: copy the code 
        uses: actions/checkout@v3

      - name: setup go 
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: build go app
        run: go build hello.go


        